services:
  - type: web
    name: Trajectoires des oiseaux marins
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=src python -m streamlit run src/movebank_seabirds/app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
